# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7fc3500daef538b7e26a32483c1c86fb303267fea93c306f689434974aa0b13265790871b51f92c6c2d8a5965e160ff02ba2701233926084d722defa568be90

test:
  secret_key_base: 44ca4e29a2d88f9d165a759552ae2710ed56f771ec182a5e3a8aaa13782e4ebfc936d8ea62074cc6b026b2976a9a22f0465b73cacb38c6cf6d92c41506729d5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
